### ISSUE TITLE
出现错误。

### ISSUE THREAD

**Issue by belth0219** [oyishi/TTui#1]
Wholly下载中 [====================] 100%
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: invalid signature: 0x80014
    at C:\Users\breat\OneDrive\Single_Addons\TTui-master\node_modules\unzip\lib\parse.js:59:13
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
Emitted 'error' event at:
    at Parse.<anonymous> (C:\Users\breat\OneDrive\Single_Addons\TTui-master\node_modules\unzip\lib\extract.js:24:10)
    at Parse.emit (events.js:182:13)
    at C:\Users\breat\OneDrive\Single_Addons\TTui-master\node_modules\unzip\lib\parse.js:60:12
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)

请教这是什么问题。。。

**Comment by FoxCD** [comment]
unzip的问题，请移步：https://github.com/FoxCD/TTui.git，下载最新版本
